# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'new_lab_dialog.ui'
##
## Created by: Qt User Interface Compiler version 6.7.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QDialog,
    QFrame, QGroupBox, QHBoxLayout, QHeaderView,
    QLabel, QLineEdit, QListView, QListWidget,
    QListWidgetItem, QPushButton, QRadioButton, QSizePolicy,
    QSpinBox, QTabWidget, QTableWidget, QTableWidgetItem,
    QVBoxLayout, QWidget)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        if not Dialog.objectName():
            Dialog.setObjectName(u"Dialog")
        Dialog.resize(1080, 600)
        self.tabWidget = QTabWidget(Dialog)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(20, 20, 1031, 531))
        self.General = QWidget()
        self.General.setObjectName(u"General")
        self.frame = QFrame(self.General)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(10, 10, 1010, 260))
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.label = QLabel(self.frame)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(40, 30, 56, 16))
        self.label_2 = QLabel(self.frame)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(40, 70, 121, 16))
        self.label_3 = QLabel(self.frame)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(40, 110, 111, 16))
        self.label_4 = QLabel(self.frame)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(40, 135, 141, 16))
        self.label_5 = QLabel(self.frame)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(450, 110, 131, 16))
        self.general_configfile_name = QLabel(self.frame)
        self.general_configfile_name.setObjectName(u"general_configfile_name")
        self.general_configfile_name.setGeometry(QRect(570, 110, 161, 16))
        self.general_human_radio = QRadioButton(self.frame)
        self.general_human_radio.setObjectName(u"general_human_radio")
        self.general_human_radio.setGeometry(QRect(200, 160, 99, 22))
        self.general_combined_radio = QRadioButton(self.frame)
        self.general_combined_radio.setObjectName(u"general_combined_radio")
        self.general_combined_radio.setGeometry(QRect(200, 190, 231, 22))
        self.general_country_combobox = QComboBox(self.frame)
        self.general_country_combobox.setObjectName(u"general_country_combobox")
        self.general_country_combobox.setGeometry(QRect(200, 25, 511, 24))
        self.general_labname_lineedit = QLineEdit(self.frame)
        self.general_labname_lineedit.setObjectName(u"general_labname_lineedit")
        self.general_labname_lineedit.setGeometry(QRect(200, 65, 511, 23))
        self.general_labcode_lineedit = QLineEdit(self.frame)
        self.general_labcode_lineedit.setObjectName(u"general_labcode_lineedit")
        self.general_labcode_lineedit.setGeometry(QRect(200, 105, 200, 23))
        self.general_country_code = QLabel(self.frame)
        self.general_country_code.setObjectName(u"general_country_code")
        self.general_country_code.setGeometry(QRect(730, 30, 56, 16))
        self.tabWidget.addTab(self.General, "")
        self.Antibiotics = QWidget()
        self.Antibiotics.setObjectName(u"Antibiotics")
        self.groupBox = QGroupBox(self.Antibiotics)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(20, 120, 490, 331))
        self.label_11 = QLabel(self.groupBox)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(10, 35, 81, 16))
        self.antibiotic_guidelines_combobox = QComboBox(self.groupBox)
        self.antibiotic_guidelines_combobox.setObjectName(u"antibiotic_guidelines_combobox")
        self.antibiotic_guidelines_combobox.setGeometry(QRect(110, 30, 371, 24))
        self.label_12 = QLabel(self.groupBox)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(10, 75, 81, 16))
        self.antibiotics_disk_radio = QRadioButton(self.groupBox)
        self.antibiotics_disk_radio.setObjectName(u"antibiotics_disk_radio")
        self.antibiotics_disk_radio.setGeometry(QRect(110, 70, 99, 22))
        self.antibiotics_mic_radio = QRadioButton(self.groupBox)
        self.antibiotics_mic_radio.setObjectName(u"antibiotics_mic_radio")
        self.antibiotics_mic_radio.setGeometry(QRect(230, 70, 99, 22))
        self.antibiotics_etest_radio = QRadioButton(self.groupBox)
        self.antibiotics_etest_radio.setObjectName(u"antibiotics_etest_radio")
        self.antibiotics_etest_radio.setGeometry(QRect(360, 70, 99, 22))
        self.antibiotic_list = QListWidget(self.groupBox)
        self.antibiotic_list.setObjectName(u"antibiotic_list")
        self.antibiotic_list.setGeometry(QRect(10, 101, 471, 181))
        self.label_13 = QLabel(self.groupBox)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(10, 298, 56, 16))
        self.antibiotics_search = QLineEdit(self.groupBox)
        self.antibiotics_search.setObjectName(u"antibiotics_search")
        self.antibiotics_search.setGeometry(QRect(80, 295, 401, 23))
        self.antibiotics_add_button = QPushButton(self.Antibiotics)
        self.antibiotics_add_button.setObjectName(u"antibiotics_add_button")
        self.antibiotics_add_button.setGeometry(QRect(520, 240, 80, 24))
        self.antibiotics_remove_button = QPushButton(self.Antibiotics)
        self.antibiotics_remove_button.setObjectName(u"antibiotics_remove_button")
        self.antibiotics_remove_button.setGeometry(QRect(520, 320, 80, 24))
        self.groupBox_2 = QGroupBox(self.Antibiotics)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(610, 120, 391, 331))
        self.antibiotic_local_list = QListWidget(self.groupBox_2)
        self.antibiotic_local_list.setObjectName(u"antibiotic_local_list")
        self.antibiotic_local_list.setGeometry(QRect(10, 100, 371, 181))
        self.label_14 = QLabel(self.groupBox_2)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(10, 300, 141, 16))
        self.num_antibiotics = QLabel(self.groupBox_2)
        self.num_antibiotics.setObjectName(u"num_antibiotics")
        self.num_antibiotics.setGeometry(QRect(160, 300, 51, 16))
        self.antibiotics_full_name = QLabel(self.groupBox_2)
        self.antibiotics_full_name.setObjectName(u"antibiotics_full_name")
        self.antibiotics_full_name.setGeometry(QRect(10, 70, 311, 16))
        self.layoutWidget = QWidget(self.Antibiotics)
        self.layoutWidget.setObjectName(u"layoutWidget")
        self.layoutWidget.setGeometry(QRect(20, 20, 495, 84))
        self.verticalLayout = QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.label_7 = QLabel(self.layoutWidget)
        self.label_7.setObjectName(u"label_7")

        self.verticalLayout.addWidget(self.label_7)

        self.label_8 = QLabel(self.layoutWidget)
        self.label_8.setObjectName(u"label_8")

        self.verticalLayout.addWidget(self.label_8)

        self.label_9 = QLabel(self.layoutWidget)
        self.label_9.setObjectName(u"label_9")

        self.verticalLayout.addWidget(self.label_9)

        self.label_10 = QLabel(self.layoutWidget)
        self.label_10.setObjectName(u"label_10")

        self.verticalLayout.addWidget(self.label_10)

        self.layoutWidget1 = QWidget(self.Antibiotics)
        self.layoutWidget1.setObjectName(u"layoutWidget1")
        self.layoutWidget1.setGeometry(QRect(30, 460, 971, 26))
        self.horizontalLayout_3 = QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.antibiotics_breakpoint_button = QPushButton(self.layoutWidget1)
        self.antibiotics_breakpoint_button.setObjectName(u"antibiotics_breakpoint_button")

        self.horizontalLayout_3.addWidget(self.antibiotics_breakpoint_button)

        self.antibiotics_expertrules_button = QPushButton(self.layoutWidget1)
        self.antibiotics_expertrules_button.setObjectName(u"antibiotics_expertrules_button")

        self.horizontalLayout_3.addWidget(self.antibiotics_expertrules_button)

        self.antibiotics_panels_button = QPushButton(self.layoutWidget1)
        self.antibiotics_panels_button.setObjectName(u"antibiotics_panels_button")

        self.horizontalLayout_3.addWidget(self.antibiotics_panels_button)

        self.antibiotics_profiles_button = QPushButton(self.layoutWidget1)
        self.antibiotics_profiles_button.setObjectName(u"antibiotics_profiles_button")

        self.horizontalLayout_3.addWidget(self.antibiotics_profiles_button)

        self.antibiotics_print_button = QPushButton(self.layoutWidget1)
        self.antibiotics_print_button.setObjectName(u"antibiotics_print_button")

        self.horizontalLayout_3.addWidget(self.antibiotics_print_button)

        self.tabWidget.addTab(self.Antibiotics, "")
        self.Locations = QWidget()
        self.Locations.setObjectName(u"Locations")
        self.label_16 = QLabel(self.Locations)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(10, 10, 841, 16))
        self.location_table_list = QTableWidget(self.Locations)
        self.location_table_list.setObjectName(u"location_table_list")
        self.location_table_list.setGeometry(QRect(10, 40, 761, 451))
        self.groupBox_3 = QGroupBox(self.Locations)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(790, 20, 221, 151))
        self.location_institutions_edit_button = QPushButton(self.groupBox_3)
        self.location_institutions_edit_button.setObjectName(u"location_institutions_edit_button")
        self.location_institutions_edit_button.setGeometry(QRect(160, 25, 50, 18))
        font = QFont()
        font.setPointSize(8)
        self.location_institutions_edit_button.setFont(font)
        self.institution_listview = QListWidget(self.groupBox_3)
        self.institution_listview.setObjectName(u"institution_listview")
        self.institution_listview.setGeometry(QRect(10, 50, 201, 91))
        self.groupBox_4 = QGroupBox(self.Locations)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(790, 180, 221, 151))
        self.location_departments_edit_button = QPushButton(self.groupBox_4)
        self.location_departments_edit_button.setObjectName(u"location_departments_edit_button")
        self.location_departments_edit_button.setGeometry(QRect(160, 25, 50, 18))
        self.location_departments_edit_button.setFont(font)
        self.department_listview = QListWidget(self.groupBox_4)
        self.department_listview.setObjectName(u"department_listview")
        self.department_listview.setGeometry(QRect(10, 50, 201, 91))
        self.groupBox_5 = QGroupBox(self.Locations)
        self.groupBox_5.setObjectName(u"groupBox_5")
        self.groupBox_5.setGeometry(QRect(790, 340, 221, 151))
        self.location_type_listview = QListWidget(self.groupBox_5)
        self.location_type_listview.setObjectName(u"location_type_listview")
        self.location_type_listview.setGeometry(QRect(10, 50, 201, 91))
        self.tabWidget.addTab(self.Locations, "")
        self.DataFields = QWidget()
        self.DataFields.setObjectName(u"DataFields")
        self.groupBox_6 = QGroupBox(self.DataFields)
        self.groupBox_6.setObjectName(u"groupBox_6")
        self.groupBox_6.setGeometry(QRect(20, 90, 481, 351))
        self.data_fields_list = QListWidget(self.groupBox_6)
        self.data_fields_list.setObjectName(u"data_fields_list")
        self.data_fields_list.setGeometry(QRect(10, 30, 251, 271))
        self.data_fields_modify_button = QPushButton(self.groupBox_6)
        self.data_fields_modify_button.setObjectName(u"data_fields_modify_button")
        self.data_fields_modify_button.setGeometry(QRect(280, 30, 181, 24))
        self.label_20 = QLabel(self.groupBox_6)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(10, 320, 121, 16))
        self.num_data_fields = QLabel(self.groupBox_6)
        self.num_data_fields.setObjectName(u"num_data_fields")
        self.num_data_fields.setGeometry(QRect(130, 320, 56, 16))
        self.encryption_button = QPushButton(self.groupBox_6)
        self.encryption_button.setObjectName(u"encryption_button")
        self.encryption_button.setGeometry(QRect(280, 60, 181, 24))
        self.groupBox_7 = QGroupBox(self.DataFields)
        self.groupBox_7.setObjectName(u"groupBox_7")
        self.groupBox_7.setGeometry(QRect(520, 90, 481, 351))
        self.layoutWidget2 = QWidget(self.groupBox_7)
        self.layoutWidget2.setObjectName(u"layoutWidget2")
        self.layoutWidget2.setGeometry(QRect(10, 30, 91, 101))
        self.verticalLayout_3 = QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.label_22 = QLabel(self.layoutWidget2)
        self.label_22.setObjectName(u"label_22")

        self.verticalLayout_3.addWidget(self.label_22)

        self.label_23 = QLabel(self.layoutWidget2)
        self.label_23.setObjectName(u"label_23")

        self.verticalLayout_3.addWidget(self.label_23)

        self.label_24 = QLabel(self.layoutWidget2)
        self.label_24.setObjectName(u"label_24")

        self.verticalLayout_3.addWidget(self.label_24)

        self.label_25 = QLabel(self.layoutWidget2)
        self.label_25.setObjectName(u"label_25")

        self.verticalLayout_3.addWidget(self.label_25)

        self.layoutWidget3 = QWidget(self.groupBox_7)
        self.layoutWidget3.setObjectName(u"layoutWidget3")
        self.layoutWidget3.setGeometry(QRect(120, 30, 111, 101))
        self.verticalLayout_4 = QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.data_fields_description = QLabel(self.layoutWidget3)
        self.data_fields_description.setObjectName(u"data_fields_description")

        self.verticalLayout_4.addWidget(self.data_fields_description)

        self.data_fields_name = QLabel(self.layoutWidget3)
        self.data_fields_name.setObjectName(u"data_fields_name")

        self.verticalLayout_4.addWidget(self.data_fields_name)

        self.data_fields_type = QLabel(self.layoutWidget3)
        self.data_fields_type.setObjectName(u"data_fields_type")

        self.verticalLayout_4.addWidget(self.data_fields_type)

        self.data_fields_len_spinbox = QSpinBox(self.layoutWidget3)
        self.data_fields_len_spinbox.setObjectName(u"data_fields_len_spinbox")
        self.data_fields_len_spinbox.setMaximumSize(QSize(51, 24))

        self.verticalLayout_4.addWidget(self.data_fields_len_spinbox)

        self.layoutWidget4 = QWidget(self.DataFields)
        self.layoutWidget4.setObjectName(u"layoutWidget4")
        self.layoutWidget4.setGeometry(QRect(20, 10, 322, 62))
        self.verticalLayout_2 = QVBoxLayout(self.layoutWidget4)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.label_17 = QLabel(self.layoutWidget4)
        self.label_17.setObjectName(u"label_17")

        self.verticalLayout_2.addWidget(self.label_17)

        self.label_18 = QLabel(self.layoutWidget4)
        self.label_18.setObjectName(u"label_18")

        self.verticalLayout_2.addWidget(self.label_18)

        self.label_19 = QLabel(self.layoutWidget4)
        self.label_19.setObjectName(u"label_19")

        self.verticalLayout_2.addWidget(self.label_19)

        self.tabWidget.addTab(self.DataFields, "")
        self.Alerts = QWidget()
        self.Alerts.setObjectName(u"Alerts")
        self.frame_2 = QFrame(self.Alerts)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setGeometry(QRect(20, 20, 991, 241))
        self.frame_2.setFrameShape(QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Raised)
        self.alerts_table_view = QTableWidget(self.frame_2)
        self.alerts_table_view.setObjectName(u"alerts_table_view")
        self.alerts_table_view.setGeometry(QRect(10, 41, 971, 191))
        self.layoutWidget5 = QWidget(self.frame_2)
        self.layoutWidget5.setObjectName(u"layoutWidget5")
        self.layoutWidget5.setGeometry(QRect(10, 10, 671, 26))
        self.horizontalLayout_4 = QHBoxLayout(self.layoutWidget5)
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.alerts_new_button = QPushButton(self.layoutWidget5)
        self.alerts_new_button.setObjectName(u"alerts_new_button")

        self.horizontalLayout_4.addWidget(self.alerts_new_button)

        self.alerts_edit_button = QPushButton(self.layoutWidget5)
        self.alerts_edit_button.setObjectName(u"alerts_edit_button")

        self.horizontalLayout_4.addWidget(self.alerts_edit_button)

        self.alerts_delete_button = QPushButton(self.layoutWidget5)
        self.alerts_delete_button.setObjectName(u"alerts_delete_button")

        self.horizontalLayout_4.addWidget(self.alerts_delete_button)

        self.alerts_sort_combobox = QComboBox(self.layoutWidget5)
        self.alerts_sort_combobox.setObjectName(u"alerts_sort_combobox")
        self.alerts_sort_combobox.setMinimumSize(QSize(301, 24))

        self.horizontalLayout_4.addWidget(self.alerts_sort_combobox)

        self.alerts_group = QGroupBox(self.Alerts)
        self.alerts_group.setObjectName(u"alerts_group")
        self.alerts_group.setGeometry(QRect(20, 270, 991, 211))
        self.alerts_group.setFlat(False)
        self.alerts_description = QLabel(self.alerts_group)
        self.alerts_description.setObjectName(u"alerts_description")
        self.alerts_description.setGeometry(QRect(20, 30, 311, 16))
        self.checkBox = QCheckBox(self.alerts_group)
        self.checkBox.setObjectName(u"checkBox")
        self.checkBox.setGeometry(QRect(480, 30, 111, 22))
        self.alerts_organism_listview = QListView(self.alerts_group)
        self.alerts_organism_listview.setObjectName(u"alerts_organism_listview")
        self.alerts_organism_listview.setGeometry(QRect(90, 70, 391, 51))
        self.label_30 = QLabel(self.alerts_group)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(20, 70, 56, 16))
        self.label_31 = QLabel(self.alerts_group)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(20, 130, 56, 16))
        self.alerts_isolates_listview = QListView(self.alerts_group)
        self.alerts_isolates_listview.setObjectName(u"alerts_isolates_listview")
        self.alerts_isolates_listview.setGeometry(QRect(90, 130, 391, 71))
        self.label_32 = QLabel(self.alerts_group)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setGeometry(QRect(510, 70, 56, 16))
        self.label_33 = QLabel(self.alerts_group)
        self.label_33.setObjectName(u"label_33")
        self.label_33.setGeometry(QRect(510, 130, 56, 16))
        self.alerts_alerts_listview = QListView(self.alerts_group)
        self.alerts_alerts_listview.setObjectName(u"alerts_alerts_listview")
        self.alerts_alerts_listview.setGeometry(QRect(580, 70, 391, 51))
        self.alerts_messages_listview = QListView(self.alerts_group)
        self.alerts_messages_listview.setObjectName(u"alerts_messages_listview")
        self.alerts_messages_listview.setGeometry(QRect(580, 130, 391, 71))
        self.label_34 = QLabel(self.alerts_group)
        self.label_34.setObjectName(u"label_34")
        self.label_34.setGeometry(QRect(600, 30, 161, 16))
        self.tabWidget.addTab(self.Alerts, "")
        self.layoutWidget6 = QWidget(Dialog)
        self.layoutWidget6.setObjectName(u"layoutWidget6")
        self.layoutWidget6.setGeometry(QRect(860, 560, 191, 31))
        self.horizontalLayout = QHBoxLayout(self.layoutWidget6)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.save_button = QPushButton(self.layoutWidget6)
        self.save_button.setObjectName(u"save_button")

        self.horizontalLayout.addWidget(self.save_button)

        self.cancel_button = QPushButton(self.layoutWidget6)
        self.cancel_button.setObjectName(u"cancel_button")

        self.horizontalLayout.addWidget(self.cancel_button)


        self.retranslateUi(Dialog)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(Dialog)
    # setupUi

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QCoreApplication.translate("Dialog", u"Dialog", None))
        self.label.setText(QCoreApplication.translate("Dialog", u"Country:", None))
        self.label_2.setText(QCoreApplication.translate("Dialog", u"Laboratory Name:", None))
        self.label_3.setText(QCoreApplication.translate("Dialog", u"Laboratory Code:", None))
        self.label_4.setText(QCoreApplication.translate("Dialog", u"Maximum 3 Characters", None))
        self.label_5.setText(QCoreApplication.translate("Dialog", u"Configuration File:", None))
        self.general_configfile_name.setText(QCoreApplication.translate("Dialog", u"TextLabel", None))
        self.general_human_radio.setText(QCoreApplication.translate("Dialog", u"Human", None))
        self.general_combined_radio.setText(QCoreApplication.translate("Dialog", u"Human, Animal, Food, Environment", None))
        self.general_country_code.setText(QCoreApplication.translate("Dialog", u"TextLabel", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.General), QCoreApplication.translate("Dialog", u"General", None))
        self.groupBox.setTitle(QCoreApplication.translate("Dialog", u"Antibiotic list", None))
        self.label_11.setText(QCoreApplication.translate("Dialog", u"Guidelines: ", None))
        self.label_12.setText(QCoreApplication.translate("Dialog", u"Test Method", None))
        self.antibiotics_disk_radio.setText(QCoreApplication.translate("Dialog", u"Disk", None))
        self.antibiotics_mic_radio.setText(QCoreApplication.translate("Dialog", u"MIC", None))
        self.antibiotics_etest_radio.setText(QCoreApplication.translate("Dialog", u"Etest", None))
        self.label_13.setText(QCoreApplication.translate("Dialog", u"Search", None))
        self.antibiotics_add_button.setText(QCoreApplication.translate("Dialog", u"->", None))
        self.antibiotics_remove_button.setText(QCoreApplication.translate("Dialog", u"<-", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("Dialog", u"Local Antibiotic List", None))
        self.label_14.setText(QCoreApplication.translate("Dialog", u"Number of antibiotics =", None))
        self.num_antibiotics.setText(QCoreApplication.translate("Dialog", u"0", None))
        self.antibiotics_full_name.setText(QCoreApplication.translate("Dialog", u"TextLabel", None))
        self.label_7.setText(QCoreApplication.translate("Dialog", u"1. Choose the antibiotics which you test in your laboratory.", None))
        self.label_8.setText(QCoreApplication.translate("Dialog", u"2. Indicate the guidelines, the test method, and the antibiotics name.", None))
        self.label_9.setText(QCoreApplication.translate("Dialog", u"3. Print and review the antibiotic breakpoints.", None))
        self.label_10.setText(QCoreApplication.translate("Dialog", u"4. Define antibiotic panels (for data entry) and antibiotic profiles (for data analysis).", None))
        self.antibiotics_breakpoint_button.setText(QCoreApplication.translate("Dialog", u"Breakpoints", None))
        self.antibiotics_expertrules_button.setText(QCoreApplication.translate("Dialog", u"Expert Rules", None))
        self.antibiotics_panels_button.setText(QCoreApplication.translate("Dialog", u"Panels", None))
        self.antibiotics_profiles_button.setText(QCoreApplication.translate("Dialog", u"Profiles", None))
        self.antibiotics_print_button.setText(QCoreApplication.translate("Dialog", u"Print", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Antibiotics), QCoreApplication.translate("Dialog", u"Antibiotics", None))
        self.label_16.setText(QCoreApplication.translate("Dialog", u"The lists on the right will change the selected rows's value when clicked.", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("Dialog", u"Institutions", None))
        self.location_institutions_edit_button.setText(QCoreApplication.translate("Dialog", u"Edit", None))
        self.groupBox_4.setTitle(QCoreApplication.translate("Dialog", u"Departments", None))
        self.location_departments_edit_button.setText(QCoreApplication.translate("Dialog", u"Edit", None))
        self.groupBox_5.setTitle(QCoreApplication.translate("Dialog", u"Location type", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Locations), QCoreApplication.translate("Dialog", u"Locations - Optional", None))
        self.groupBox_6.setTitle(QCoreApplication.translate("Dialog", u"Fields", None))
        self.data_fields_modify_button.setText(QCoreApplication.translate("Dialog", u"Modify List", None))
        self.label_20.setText(QCoreApplication.translate("Dialog", u"Number  of Fields =", None))
        self.num_data_fields.setText(QCoreApplication.translate("Dialog", u"0", None))
        self.encryption_button.setText(QCoreApplication.translate("Dialog", u"Encryption", None))
        self.groupBox_7.setTitle(QCoreApplication.translate("Dialog", u"Field Summary", None))
        self.label_22.setText(QCoreApplication.translate("Dialog", u"Description", None))
        self.label_23.setText(QCoreApplication.translate("Dialog", u"Name", None))
        self.label_24.setText(QCoreApplication.translate("Dialog", u"Type", None))
        self.label_25.setText(QCoreApplication.translate("Dialog", u"Length", None))
        self.data_fields_description.setText(QCoreApplication.translate("Dialog", u"TextLabel", None))
        self.data_fields_name.setText(QCoreApplication.translate("Dialog", u"TextLabel", None))
        self.data_fields_type.setText(QCoreApplication.translate("Dialog", u"TextLabel", None))
        self.label_17.setText(QCoreApplication.translate("Dialog", u"Your data fields appear below.", None))
        self.label_18.setText(QCoreApplication.translate("Dialog", u"Make any necessary changes.", None))
        self.label_19.setText(QCoreApplication.translate("Dialog", u"If you want to add or remove fields, select 'Modify list'.", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.DataFields), QCoreApplication.translate("Dialog", u"Data Fields - Optional", None))
        self.alerts_new_button.setText(QCoreApplication.translate("Dialog", u"New", None))
        self.alerts_edit_button.setText(QCoreApplication.translate("Dialog", u"Edit", None))
        self.alerts_delete_button.setText(QCoreApplication.translate("Dialog", u"Delete", None))
        self.alerts_group.setTitle(QCoreApplication.translate("Dialog", u"Organism", None))
        self.alerts_description.setText(QCoreApplication.translate("Dialog", u"Alert", None))
        self.checkBox.setText(QCoreApplication.translate("Dialog", u"Active Rule", None))
        self.label_30.setText(QCoreApplication.translate("Dialog", u"Organisms", None))
        self.label_31.setText(QCoreApplication.translate("Dialog", u"Isolates", None))
        self.label_32.setText(QCoreApplication.translate("Dialog", u"Alerts", None))
        self.label_33.setText(QCoreApplication.translate("Dialog", u"Messages", None))
        self.label_34.setText(QCoreApplication.translate("Dialog", u"Priority", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Alerts), QCoreApplication.translate("Dialog", u"Alerts - Optional", None))
        self.save_button.setText(QCoreApplication.translate("Dialog", u"Save", None))
        self.cancel_button.setText(QCoreApplication.translate("Dialog", u"Cancel ", None))
    # retranslateUi

